shared_buffers = 512MB
effective_cache_size = 1536MB
work_mem = 16MB
maintenance_work_mem = 256MB
wal_buffers = 16MB
checkpoint_completion_target = 0.9
max_worker_processes = 8
max_parallel_workers_per_gather = 2
max_parallel_workers = 4
max_connections = 20
log_min_duration_statement = 1000
ssl = off
password_encryption = scram-sha-256